#pragma once

#define VIA_QMK_RGBLIGHT_ENABLE 
#define VIA_CUSTOM_LIGHTING_ENABLE
#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 1536
#define WEAR_LEVELING_BACKING_SIZE 3200
#define WEAR_LEVELING_LOGICAL_SIZE 1600
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
