#pragma once

#define VIA_QMK_RGBLIGHT_ENABLE 
#define VIA_CUSTOM_LIGHTING_ENABLE
#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 1536
#define WEAR_LEVELING_SN32_EMULATION_PAGE_COUNT 49
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
